batch_size: 2                        # Batch size
learning_rate: 0.00005               # Learning rate
epochs: 1                          # Number of epochs
save_path: "C:/Users/Leoni/Athlete_nutrition/FoodSeg_mask2former/checkpoints"
load_checkpoint: null                # Checkpoint to load (or null)
log_dir: "C:/Users/Leoni/Athlete_nutrition/FoodSeg_mask2former/tb_logs"
